### ISSUE TITLE
[BUG] Packer image build fails on a cloud-provider instance

### ISSUE THREAD

**Issue by svergnaud-csgroup** [COPRS/reference-system-software#32]
**Describe the bug**
When running the following command, packer build process ends in KVM error : **gtk initialization failed**
```ansible-playbook playbooks/image.yaml -i inventory/cps-it-ivv/hosts.ini```

**To Reproduce**
1. Create a cloud provider instance
2. Clone the repo
3. Follow the readme file
4. Execute the following command:
```ansible-playbook playbooks/image.yaml -i inventory/cps-it-ivv/hosts.ini```

**Expected behavior**
Packer build ends in success.

**Additional context**
It seems that the accelerator used during build process causes the problem:
```yaml
...
"net_device": "virtio-net",
"accelerator": "kvm",  <==
"disk_image": true,
...
```
Cloud provider instances (AWS, FE, OVH) are not capable of nested virtualization so that trying to start KVM in an openstack virtual instance will always fails.
Changing the parameter to **none** seems to solve the problem BUT to slow down the building process (especially network features):
```yaml
...
"net_device": "virtio-net",
"accelerator": "none",  <==
"disk_image": true,
...
```
